# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['run_app.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('src/audit_merge', 'audit_merge'),
    ],
    hiddenimports=[
        'textual',
        'textual.widgets',
        'textual.widgets._tab_pane',
        'textual.widgets._button',
        'textual.widgets._input',
        'textual.widgets._label',
        'textual.widgets._select',
        'textual.widgets._radio_set',
        'textual.widgets._radio_button',
        'textual.widgets._rich_log',
        'textual.widgets._progress_bar',
        'textual.widgets._tabs',
        'textual.widgets._data_table',
        'textual.widgets._static',
        'textual.widgets._directory_tree',
        'textual.screen',
        'textual.app',
        'textual.containers',
        'textual.binding',
        'textual.message',
        'textual.reactive',
        'rich',
        'rich.text',
        'rich.panel',
        'rich.table',
        'rich.console',
        'openpyxl',
        'openpyxl.worksheet',
        'openpyxl.cell',
        'openpyxl.styles',
        'rapidfuzz',
        'rapidfuzz.fuzz',
        'rapidfuzz.process',
        'dateutil',
        'dateutil.parser',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='audit-merge',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='assets/icon.ico' if os.path.exists('assets/icon.ico') else None,
)